name: Build kernel

on:
  push:

jobs:
  cebu:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build
      run: |
        ./build.sh cebu

    - name: Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Kernel - Flashable
        path: AnyKernel3/*.zip
        if-no-files-found: error
